function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1))
        ;[array[i], array[j]] = [array[j], array[i]]
    }
    return array
}

var memory_trialnumber = 1

var memory_preloadstims = {
    type: jsPsychPreload,
    images: stimuli_list.map((a) => "stimuli/" + a.Item),
    message: "Please wait while the experiment is loading in (it can take a few minutes).",
}

var memory_fixation = {
    type: jsPsychHtmlKeyboardResponse,
    stimulus: "<div  style='font-size:500%; position:fixed; text-align: center; top:50%; bottom:50%; right:20%; left:20%'>+</div>",
    choices: ["s"],
    trial_duration: 750,
    save_trial_parameters: { trial_duration: true },
    data: { screen: "memory_fixation" },
}

var memory_showimage = {
    type: jsPsychImageKeyboardResponse,
    stimulus: function () {
        return "stimuli/" + jsPsych.evaluateTimelineVariable("Item")
    },
    stimulus_width: function () {
        let ratio = jsPsych.evaluateTimelineVariable("Width") / jsPsych.evaluateTimelineVariable("Height")
        return Math.round(Math.min(0.9 * window.innerHeight * ratio, 0.9 * window.innerWidth))
    },

    stimulus_height: function () {
        let ratio = jsPsych.evaluateTimelineVariable("Width") / jsPsych.evaluateTimelineVariable("Height")
        return Math.round(Math.min((0.9 * window.innerWidth) / ratio, 0.9 * window.innerHeight))
    },
    trial_duration: 2000,
    choices: ["s"],
    save_trial_parameters: { trial_duration: true },
    data: function () {
        return {
            screen: "memory_image",
            trial_number: memory_trialnumber,
            item: jsPsych.evaluateTimelineVariable("Item"),
        }
    },
    on_finish: function () {
        memory_trialnumber += 1
    },
}

var memory_ratings = {
    type: jsPsychSurvey,
    survey_json: {
        goNextPageAutomatic: true,
        showQuestionNumbers: false,
        completeText: "Continue",
        showNavigationButtons: true,
        title: function () {
            return "Rating - " + Math.round(((memory_trialnumber - 1) / stimuli_list.length) * 100) + "%"
        },
        description: "Do you recognise the artwork?",
        pages: [
            {
                elements: [
                    {
                        type: "radiogroup",
                        name: "Recognition",
                        title: "I recognise this artwork from the previous study",
                        isRequired: true,
                        choices: ["Yes", "No"],
                    },

                    {
                        type: "rating",
                        name: "DisplayLabel",
                        title: "In the previous study, this artwork was labelled as...",
                        isRequired: true,
                        visibleIf: "{Recognition} = 'Yes'",
                        displayMode: "buttons",
                        rateValues: ["Original", "AI-Generated", "Human Forgery"],
                    },

                    {
                        type: "slider",
                        name: "Reality",
                        title: "In the previous study, I thought this artwork was...",
                        description: "Was the artwork painted by a person or generated by an AI?",
                        isRequired: true,
                        visibleIf: "{Recognition} = 'Yes'",

                        min: -100,
                        max: 100,
                        step: 1,
                        customLabels: [
                            {
                                value: -100,
                                text: " AI-Generated",
                            },
                            {
                                value: 100,
                                text: "Human Creation",
                            },
                        ],
                    },
                    {
                        type: "slider",
                        name: "Authenticity",
                        title: "In the previous study, I thought this artwork was a...",
                        description: "Is the artwork original and unique, or was it made to copy an existing artwork or artist?",
                        isRequired: true,
                        visibleIf: "{Recognition} = 'Yes'",

                        min: -100,
                        max: 100,
                        step: 1,
                        customLabels: [
                            {
                                value: -100,
                                text: "Copy / Forgery",
                            },
                            {
                                value: 100,
                                text: "Original Creation",
                            },
                        ],
                    },
                    /*{
                        type: "slider",
                        name: "Familiarity",
                        title: "This artwork is...",
                        description: "To what extent do you recall seeing this artwork in the previous study?",
                        isRequired: true,
                        visibleIf: "{Recognition} = 'Yes'",
                        
                        min: -100,
                        max: 100,
                        step: 1,
                        customLabels: [
                            {
                                value: -100,
                                text: "Unfamiliar",
                            },
                            {
                                value: 100,
                                text: "Familiar",
                            },
                        ],
                      
                    }, */
                ],
            },
        ],
    },
    data: {
        screen: "memory_ratings",
    },
}

var memory_phase = {
    timeline_variables: shuffleArray(stimuli_list),
    timeline: [memory_fixation, memory_showimage, memory_ratings],
}
