---
title: "FakeArt - Data Analysis"
editor: source
editor_options: 
  chunk_output_type: console
format:
  html:
    code-fold: true
    self-contained: false
    toc: true
execute:
  cache: true
---

## Data Preparation

```{r}
#| warning: false
#| error: false

library(tidyverse)
library(easystats)
library(patchwork)
library(ggside)
library(ggdist)
library(brms)
library(cogmod)

options(mc.cores = parallel::detectCores() - 2)

df <- read.csv("../data/data_participants.csv")
```





## Individual Parameters

```{r}
#| eval: false

get_grouplevel <- function(m, outcome = "Beauty", extra_params = "mu") {
  data <- get_data(m)
  
  df_individual <- data.frame()
  batches <- split(unique(data$Participant),  ceiling(seq_along(unique(data$Participant)) / 50))
  for(batch in 1:length(batches)) {
    cat("\nProcessing batch ", batch, " of ", length(batches), "...\n")
    data_subset <- data[data$Participant %in% batches[[batch]], ]
    
    params <- c(extra_params, insight::find_auxiliary(m))
    params <- params[!params %in% c("pex", "bex", "pmid", "disc")]
    
    for(p in params) {
      cat(".")
      c_baseline <- estimate_means(m, by = c("Participant", "Condition"), 
                                   backend = "marginaleffects", iterations = 100,  
                                   data = data_subset, test = NULL, ci = NULL, 
                                   dispersion = TRUE, predict = p) |>
        filter(Condition == "Human Original") |>
        mutate(Parameter = paste0("Baseline_", str_replace(p, "response", "resp"))) |>
        select(-Condition)
      names(c_baseline)[!names(c_baseline) %in% c("Participant", "MAD", "Parameter")] <- "Median"
      
      
      c_condition <- estimate_contrasts(m, contrast = "Condition", by = c("Participant"), 
                                        backend = "marginaleffects", iterations = 100, 
                                        data = data_subset, test = NULL, ci = NULL,
                                        dispersion = TRUE, predict = p) |>
      mutate(Level1 = case_when(Level1 == "AI-Generated" ~ "AI",
                                Level1 == "Human Original" ~ "Ori",
                                .default = "Forg"),
             Level2 = case_when(Level2== "AI-Generated" ~ "AI",
                                Level2 == "Human Original" ~ "Ori",
                                .default = "Forg"), 
             Parameter = paste0(Level1, Level2, "_", str_replace(p, "response", "resp"))) |> 
      select(Participant, Parameter, Median, MAD)
      
      df_individual <- bind_rows(df_individual, c_baseline, c_condition)
    }
  }
  df_individual$Outcome <- outcome
  df_individual
}

```


```{r}
#| eval: false

library(future)
library(future.apply)

m_beauty <- readRDS("models/Beauty.rds")
m_valence <- readRDS("models/Valence.rds")
m_meaning <- readRDS("models/Meaning.rds")
m_worth <- readRDS("models/Worth.rds")

m_reality <- readRDS("models/Reality.rds")
m_authenticity <- readRDS("models/Authenticity.rds")

rez <- get_grouplevel(m_reality, outcome = "Reality", extra_params = c("response", "mu"))

# 1. Set up 2 background workers (since we have 2 models)
plan(multisession, workers = 4)

# 2. Define the tasks
tasks <- list(
  list(model = m_beauty, outcome = "Beauty", extra_params = c("response", "mu")),
  list(model = m_valence, outcome = "Valence", extra_params = "response"),
  list(model = m_meaning, outcome = "Meaning", extra_params = c("response", "mu")),
  list(model = m_worth, outcome = "Worth", extra_params = "response"),
  list(model = m_reality, outcome = "Reality", extra_params = c("response", "mu")),
  list(model = m_authenticity, outcome = "Authenticity", extra_params = c("response", "mu"))
)

# 3. Run the two models in parallel
results_list <- future_lapply(tasks, function(task) {
  get_grouplevel(task$model, outcome = task$outcome, extra_params = task$extra_params)
}, future.seed = TRUE)

df_individual <- bind_rows(results_list)

write.csv(df_individual, "../data/data_grouplevel.csv", row.names = FALSE)
```

### Reliability

```{r}
df_individual <- read.csv("../data/data_grouplevel.csv")
```


### Feature Reduction

```{r}
df_wide <- df_individual |> 
  mutate(Parameter = paste0(Outcome, "_", Parameter)) |>
  select(-MAD, -Outcome) |>
  pivot_wider(names_from = "Parameter", values_from = c("Median")) |> 
  standardize(exclude = "Participant")

nfac <- n_factors(select(df_wide, -Participant))
plot(nfac)

rez <- factor_analysis(select(df_wide, -Participant), n = 4, sort = TRUE)
plot(rez)

df_wide <- cbind(df_wide, predict(rez))
```

```{r}
df_wide |>
  correlation(p_adjust = "none", redundant = TRUE) |>
  cor_sort() |>
  mutate(Sig = ifelse(p < .05, "Significant", "N.S.")) |>
  ggplot(aes(x=Parameter1, y=Parameter2)) +
  geom_tile(aes(fill = r, alpha = Sig)) +
  scale_fill_gradient2(low = "#1D9AF5", mid = "white", high = "#F51D56", midpoint = 0, limits = c(-1, 1)) +
  scale_alpha_manual(values = c("Significant" = 1, "N.S." = 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
library(tidygraph)
library(ggraph)
library(EGAnet)

rez <- EGAnet::bootEGA(select(df_wide, -Participant), EGA.type 
 = "EGA",  corr  = "pearson", plot.itemStability = FALSE)
plot(rez)
```


## Correlates

```{r}
df_all <- full_join(df, df_wide, by = "Participant")
```

```{r}
select(df_all, all_of(names(df_wide))) |> 
  correlation(
    data2 = select(df_all, 
                   ManipulationDistrust, 
                   BAIT_ArtRealistic, BAIT_Positive, BAIT_Negative, BAIT_Total,
                   starts_with("MINT"), -MINT_AttentionCheck), p_adjust = "none") |>
  cor_sort() |>
  mutate(Sig = ifelse(p < .05, "Significant", "N.S.")) |>
  ggplot(aes(x=Parameter1, y=Parameter2)) +
  geom_tile(aes(fill = r, alpha = Sig)) +
  scale_fill_gradient2(low = "#1D9AF5", mid = "white", high = "#F51D56", midpoint = 0, limits = c(-1, 1)) +
  scale_alpha_manual(values = c("Significant" = 1, "N.S." = 0.2)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
